-- 0001_init.sql
create extension if not exists pgcrypto;

-- Helpers
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

-- User settings
create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  privacy_mode boolean not null default false,
  preferred_language text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_user_settings_updated
before update on public.user_settings
for each row execute function public.set_updated_at();

-- App profiles (tone/format rules)
create table if not exists public.app_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  app_key text not null, -- e.g. 'gmail' | 'slack' | 'docs' | 'generic'
  tone text not null default 'professional', -- freeform allowed in MVP
  language text not null default 'en',
  formatting jsonb not null default '{}'::jsonb, -- e.g. { "bullets": true, "max_length": 800 }
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_app_profile_user_app unique(user_id, app_key)
);

create index if not exists idx_app_profiles_user on public.app_profiles(user_id);

create trigger trg_app_profiles_updated
before update on public.app_profiles
for each row execute function public.set_updated_at();

-- Personal dictionary
create table if not exists public.dictionary_terms (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  term text not null,
  phonetic text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_dictionary_user_term unique(user_id, term)
);

create index if not exists idx_dictionary_user on public.dictionary_terms(user_id);

create trigger trg_dictionary_updated
before update on public.dictionary_terms
for each row execute function public.set_updated_at();

-- Snippets
create table if not exists public.snippets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  trigger_phrase text null, -- e.g. "insert intro"
  variables jsonb not null default '[]'::jsonb, -- ["name","date"] etc
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_snippets_user on public.snippets(user_id);

create trigger trg_snippets_updated
before update on public.snippets
for each row execute function public.set_updated_at();

-- Workflows (simple MVP: JSON steps)
create table if not exists public.workflows (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text null,
  tags text[] not null default '{}',
  steps jsonb not null default '[]'::jsonb, -- [{prompt, output_format}, ...]
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_workflows_user on public.workflows(user_id);

create trigger trg_workflows_updated
before update on public.workflows
for each row execute function public.set_updated_at();

-- Dictation sessions (idempotency + debugging)
create table if not exists public.dictation_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid null references public.app_profiles(id) on delete set null,
  client_session_id text not null, -- generated by extension
  status text not null default 'created', -- created|refined|inserted|failed
  input_text text null,
  refined_text text null,
  error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_dictation_user_client_session unique(user_id, client_session_id)
);

create index if not exists idx_dictation_user on public.dictation_sessions(user_id);

create trigger trg_dictation_updated
before update on public.dictation_sessions
for each row execute function public.set_updated_at();

-- Usage events (metering)
create table if not exists public.usage_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null, -- 'stt_words' | 'refine_words' | 'dictation_seconds'
  quantity int not null check (quantity >= 0),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_usage_user_time on public.usage_events(user_id, created_at desc);

-- Stripe customer mapping
create table if not exists public.stripe_customers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text not null unique,
  created_at timestamptz not null default now()
);

-- Stripe subscriptions
create table if not exists public.stripe_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_subscription_id text not null unique,
  status text not null, -- active|trialing|past_due|canceled|incomplete...
  price_id text not null,
  current_period_end timestamptz null,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stripe_sub_user on public.stripe_subscriptions(user_id);

create trigger trg_stripe_sub_updated
before update on public.stripe_subscriptions
for each row execute function public.set_updated_at();
